### ISSUE TITLE
Error occurred when computing the set of kmer pairs

### ISSUE THREAD

**Issue by hungweichen0327** [KamilSJaron/smudgeplot#171]
Dear community,

After I used jellyfish to calculate kmer frequencies, I followed the manual of smudgeplot with jellyfish (https://github.com/KamilSJaron/smudgeplot/wiki/manual-of-smudgeplot-with-jellyfish).

When I ran the script `jellyfish dump -c -L $L -U $U kmer_counts.jf | smudgeplot.py hetmers -o kmer_pairs`, the error occurred:

`
Running smudgeplot v0.4.0dev
Task: hetmers
Traceback (most recent call last):
  File "/home/hwc/miniforge3/envs/genomescope2/bin/smudgeplot.py", line 444, in <module>
    main()
  File "/home/hwc/miniforge3/envs/genomescope2/bin/smudgeplot.py", line 356, in main
    plot_args += " " + args.infile
                 ~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
`

How do I solve this problem? 

Thank you for the help.

**Comment by hungweichen0327** [comment]
Thank you.
