### ISSUE TITLE
error in saving kmers when decreasing number of bins

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#28]
When  I run 

```
smudgeplot plot kmer_pairs_coverages.tsv -o Tps_middle_pe_raw_reads -t "Timema poppensis" -kmer_file kmer_pairs_sequences.tsv
```

I get the following error. Needs to be fixed

```
INFO:root:Running smudgeplot v0.1.3 beta3-development
INFO:root:Task: plot
INFO:root:loading kmers
INFO:root:calculating initial 1n coverage estimate
INFO:root:initial 1n coverage estimate 23.62
INFO:root:coverage range for smudgeplot: 31 - 236
INFO:root:calculating hist with nbins: 40
WARNING:root:detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to 35
INFO:root:calculating hist with nbins: 35
WARNING:root:detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to 30
INFO:root:calculating hist with nbins: 30
WARNING:root:detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to 25
INFO:root:calculating hist with nbins: 25
INFO:root:final 1n coverage estimate 24.00
INFO:root:saving kmers in smudges Tps_middle_pe_raw_reads_kmers_in_smudge_*.txt
Traceback (most recent call last):
  File "/home/kjaron/bin/smudgeplot", line 4, in <module>
    __import__('pkg_resources').run_script('smudgeplot-KamilSJaron===0.1.13devN', 'smudgeplot')
  File "/software/lib/python3.5/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/Home/kjaron/.local/lib/python3.5/site-packages/smudgeplot_KamilSJaron-0.1.13devN-py3.5.egg/EGG-INFO/scripts/smudgeplot", line 104, in <module>
    main()
  File "/Home/kjaron/.local/lib/python3.5/site-packages/smudgeplot_KamilSJaron-0.1.13devN-py3.5.egg/EGG-INFO/scripts/smudgeplot", line 98, in main
    plot(parser.arguments)
  File "/Home/kjaron/.local/lib/python3.5/site-packages/smudgeplot_KamilSJaron-0.1.13devN-py3.5.egg/EGG-INFO/scripts/smudgeplot", line 69, in plot
    smudge.saveKmersFromSmudges()
  File "/Home/kjaron/.local/lib/python3.5/site-packages/smudgeplot_KamilSJaron-0.1.13devN-py3.5.egg/smudgeplot/smudgedata.py", line 211, in saveKmersFromSmudges
    assigned_smudge = coor_smudge_dict[(y_coord, x_coord)]
KeyError: (25, 20)
```

**Comment by KamilSJaron** [comment]
Can not be reproduced. Seems like this problem was accidentally resolved during the development of other things.
